name: >-
  ephemeral_ephemeral-kube-sameera-2025-12-09-1_app_74afe68_ephemeral_env
  Pipeline (Skyu Generated)
'on':
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - .github/workflows/**
      - .trivyignore
      - Readme.md
      - README.md
  workflow_dispatch: {}
  repository_dispatch:
    types: pipeline_df6f2156-6e66-416f-9f38-0f4a02a80bf6
env:
  ENCODED_PIPELINE_SECRET: >-
    ${{secrets.LAMBDADOCKERTEST_EPHEMERAL_EPHEMERALKUBESAMEERA202512091_APP_74AFE68_EPHEMERAL_ENV}}
  COMMIT_ID: ${{github.event.client_payload.commitId || github.sha || github.run_id}}
  BRANCH_NAME: >-
    ${{github.event.client_payload.branchName || github.event.branch ||
    github.ref_name}}
  DEPLOY_STEP_SHOULD_DEPLOY: 'true'
jobs:
  build-and-push:
    name: build-and-push
    steps:
      - name: 'Run :: Start'
        run: |2-

              echo " Starting GitHub Action!" && 
              echo "STEPS_CAN_PROCEED=true" >> $GITHUB_ENV
              
      - name: 'Run :: Decoding Secrets'
        run: |2-

                if [ ! -x "$(command -v jq)" ]; then
                  echo "jq not found, installing..."
                  sudo apt-get update
                  sudo apt-get install -y jq
                fi
                echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
                
      - name: 'Run :: Checkout repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Run :: Checkout Specific Commit'
        env:
          COMMIT_ID: ${{ github.event.client_payload.commitId }}
          BRANCH_NAME: ${{ github.event.client_payload.branchName }}
        if: >-
          ${{ github.event.client_payload.commitId != null ||
          github.event.client_payload.branchName != null }}
        run: |2-

              echo "Starting the checkout process..."
              git fetch --all
              if [ -n "$COMMIT_ID" ]; then
                echo "Commit ID provided: $COMMIT_ID"
                git checkout $COMMIT_ID || true
                echo "Checked out to commit ID: $COMMIT_ID"
              elif [ -n "$BRANCH_NAME" ]; then
                echo "Branch name provided: $BRANCH_NAME"
                git checkout $BRANCH_NAME || true
                echo "Checked out to branch: $BRANCH_NAME"

                #Updating the commit Id
                ACTUAL_COMMIT_ID=$(git rev-parse HEAD)
                echo "Changing CommitId: $ACTUAL_COMMIT_ID"
                echo "COMMIT_ID=$ACTUAL_COMMIT_ID" >> $GITHUB_ENV
              else
                echo "Skipping checkout..."
              fi
            
      - name: 'Run :: Login to Dockerhub'
        run: >-
          echo "${{ env.DOCKER_PASSWORD }}" | docker login -u "${{
          env.DOCKER_USERNAME }}" --password-stdin docker.io
      - name: 'Run :: Check if image already exists'
        id: check-image-existence-step-id
        run: |2-

              if docker pull ${{ env.IMAGE_NAME }}:${{env.COMMIT_ID}} >/dev/null 2>&1; 
              then
                echo "Image exists in registry."
                echo "STEPS_CAN_PROCEED=false" >> $GITHUB_ENV
              else
                echo "Image does not exist in registry."
                echo "STEPS_CAN_PROCEED=true" >> $GITHUB_ENV
              fi
              
      - name: 'Run :: Build With Docker'
        run: >-
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.COMMIT_ID }} -f
          ${{env.DOCKER_FILE_PATH}} --build-arg BUILT_WITH=SKYU${{
          env.DOCKER_BUILD_ARGS }} ${{env.DOCKER_BUILD_CONTEXT}}
        if: ${{ env.STEPS_CAN_PROCEED == 'true' }}
      - name: 'Run :: Trivy vulnerability scanner'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.COMMIT_ID }}
          format: ${{env.TRIVY_RESULT_FORMAT}}
          output: ${{ env.COMMIT_ID }}-image-vulnerability-report.json
          exit-code: ${{env.TRIVY_SCAN_EXIT_CODE}}
          vuln-type: os,library
          severity: ${{env.SCAN_SEVERITY}}
          hide-progress: true
          timeout: 30m
        if: ${{ env.STEPS_CAN_PROCEED == 'true' }}
      - name: 'Run :: Evaluate Trivy Results'
        run: |2-

              # Minifying Json
              jq -c '.' ${{ env.COMMIT_ID }}-image-vulnerability-report.json > ${{ env.COMMIT_ID }}-image-vulnerability-report.min.json
              trivy_result=$(cat "${{ env.COMMIT_ID }}-image-vulnerability-report.min.json")

              # Set the desired severity level
              desiredSeverity="${{ env.SCAN_SEVERITY }}"
              IFS=',' read -ra severities <<< "$desiredSeverity"  # Split the severity string

              # Print the tags array for debugging
              jq '.runs[0].tool.driver.rules[].properties.tags' "${{ env.COMMIT_ID }}-image-vulnerability-report.json"

              VULNERABILITY_COUNT=0

              for severity in "${severities[@]}"; do
                count=$(jq --arg severity "$severity" '.runs[0].tool.driver.rules | map(select(.properties.tags and (.properties.tags | map(tostring) | index($severity) // empty))) | length' "${{ env.COMMIT_ID }}-image-vulnerability-report.json")
                echo "Number of $severity vulnerabilities: $count"
                VULNERABILITY_COUNT=$((VULNERABILITY_COUNT + count))
              done

              echo "Total Number of vulnerabilities: $VULNERABILITY_COUNT"

              if [ "$VULNERABILITY_COUNT" -gt 0 ]; then
                echo "STEPS_CAN_PROCEED=false" >> $GITHUB_ENV
                echo "VULNERABILITY_COUNT=$VULNERABILITY_COUNT" >> $GITHUB_ENV
              fi
              echo "ARE_TRIVY_RESULTS_EVALUATED=true" >> $GITHUB_ENV
              
        if: ${{ env.STEPS_CAN_PROCEED == 'true' }}
      - name: 'Run :: Upload Trivy Result To S3'
        env:
          RUN_ID: ${{ github.run_id }}
        run: |2-


              # Minifying Json
              jq -c '.' ${{ env.COMMIT_ID }}-image-vulnerability-report.json > ${{ env.COMMIT_ID }}-image-vulnerability-report.min.json

              # Uploading Minified Trivy Resuls
              response=$(curl -X POST -F 'file=@${{ env.COMMIT_ID }}-image-vulnerability-report.min.json' -F 'provider=aws' -F 'resourceType=image-vulnerability-report' -F 'cloudStoragePath=/${{ env.PIPELINE_APPLICATION_ID }}/image-vulnerability-reports/' -F 'pipelineRunId=${{ env.RUN_ID }}'  -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-environment-id: ${{ env.PIPELINE_ENVIRONMENT_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-resource-id: ${{ env.PIPELINE_APPLICATION_ID }}' -H 'x-auth-by: sa' -H 'Content-Type: multipart/form-data'  "${{ env.S3_UPLOAD_ENDPOINT }}")

              if echo "$response" | grep -q '"success":true'; then
                echo "SUCCESS :: $response"
              else
                echo "FAILED :: $response"
              fi
              
              if [ -f ".trivyignore" ]; then
                # Uploading trivyignore file
                trivyignoreResponse=$(curl -X POST -F 'file=@.trivyignore' -F 'provider=aws' -F 'resourceType=trivy-ignore' -F 'cloudStoragePath=/${{ env.PIPELINE_APPLICATION_ID }}/trivy-ignore-file/${{ env.COMMIT_ID }}/' -F 'pipelineRunId=${{ env.RUN_ID }}'  -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-environment-id: ${{ env.PIPELINE_ENVIRONMENT_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-resource-id: ${{ env.PIPELINE_APPLICATION_ID }}' -H 'x-auth-by: sa' -H 'Content-Type: multipart/form-data'  "${{ env.S3_UPLOAD_ENDPOINT }}")

                if echo "$trivyignoreResponse" | grep -q '"success":true'; then
                  echo "SUCCESS :: $trivyignoreResponse"
                else
                  echo "FAILED :: $trivyignoreResponse"
                fi

              else
                echo ".trivyignore file not found. Skipping the upload."
              fi
              
        if: ${{ env.ARE_TRIVY_RESULTS_EVALUATED == 'true' }}
      - name: 'Run :: Check Pipeline Safety'
        run: |2-

              if [ "${{ env.VULNERABILITY_COUNT }}" -gt 0 ]; then
                echo "UN-SAFE to continue Pipeline"
                exit 1
              else
                echo "SAFE to continue Pipeline"
              fi
              
      - name: 'Run :: Build, tag, and push image'
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.COMMIT_ID }}
        if: ${{ env.STEPS_CAN_PROCEED == 'true' }}
    needs: []
    outputs:
      stepsCanProceed: ${{ env.STEPS_CAN_PROCEED }}
    permissions: write-all
    runs-on: ubuntu-latest
  deploy:
    name: deploy
    steps:
      - name: 'Run :: Start'
        run: |2-

              echo " Starting GitHub Action!" && 
              echo "STEPS_CAN_PROCEED=true" >> $GITHUB_ENV
              
      - name: 'Run :: Decoding Secrets'
        run: |2-

                if [ ! -x "$(command -v jq)" ]; then
                  echo "jq not found, installing..."
                  sudo apt-get update
                  sudo apt-get install -y jq
                fi
                echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
                
      - name: 'Run :: Checkout repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Run :: Checkout Specific Commit'
        env:
          COMMIT_ID: ${{ github.event.client_payload.commitId }}
          BRANCH_NAME: ${{ github.event.client_payload.branchName }}
        if: >-
          ${{ github.event.client_payload.commitId != null ||
          github.event.client_payload.branchName != null }}
        run: |2-

              echo "Starting the checkout process..."
              git fetch --all
              if [ -n "$COMMIT_ID" ]; then
                echo "Commit ID provided: $COMMIT_ID"
                git checkout $COMMIT_ID || true
                echo "Checked out to commit ID: $COMMIT_ID"
              elif [ -n "$BRANCH_NAME" ]; then
                echo "Branch name provided: $BRANCH_NAME"
                git checkout $BRANCH_NAME || true
                echo "Checked out to branch: $BRANCH_NAME"

                #Updating the commit Id
                ACTUAL_COMMIT_ID=$(git rev-parse HEAD)
                echo "Changing CommitId: $ACTUAL_COMMIT_ID"
                echo "COMMIT_ID=$ACTUAL_COMMIT_ID" >> $GITHUB_ENV
              else
                echo "Skipping checkout..."
              fi
            
      - name: 'Run :: Ephemeral Deploy and Notify Resource Service'
        env:
          RUN_ID: ${{ github.run_id }}
          COMMIT_USER: ${{ github.event.head_commit.author.name }}
          COMMIT_TIME: ${{ github.event.head_commit.timestamp }}
          COMMIT_MESSAGE: >-
            ${{ github.event.head_commit.message ||
            github.event.client_payload.commitMessage }}
        run: |2-

              if [ -z "$COMMIT_MESSAGE" ]; then
                COMMIT_MESSAGE=$(git log -1 --pretty=%B | tr '\n' ' ')
                echo "Fetched commit message: $COMMIT_MESSAGE"
                echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
              fi
            
              response=$(curl -X PATCH -d "imageRegistryURL=${{ env.IMAGE_NAME }}&appVersionId=${{ env.DEPLOYMENT_APP_VERSION_ID }}&tag=${{ env.COMMIT_ID }}&containerName=${{ env.DEPLOYMENT_CONTAINER_NAME }}&shouldDeploy=${{env.DEPLOY_STEP_SHOULD_DEPLOY}}&pipelineRunId=${{ env.RUN_ID }}&commitDetails[commitHash]=${{ env.COMMIT_ID }}&commitDetails[commitAvatar]=https://github.com/$COMMIT_USER.png&commitDetails[commitTime]=$COMMIT_TIME&commitDetails[commitMessage]=$COMMIT_MESSAGE&commitDetails[commitUser]=$COMMIT_USER"  -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-environment-id: ${{ env.PIPELINE_ENVIRONMENT_ID }}' -H 'x-application-id: ${{ env.PIPELINE_APPLICATION_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-resource-id: ${{ env.PIPELINE_APPLICATION_ID }}' -H 'x-auth-by: sa' -H 'Content-Type: application/x-www-form-urlencoded'  "${{ env.DEPLOYMENT_ENDPOINT }}")
              
              status_code=$?

              if [ $status_code -eq 0 ]; then
                if echo "$response" | grep -q '"success":true'; then
                  echo "SUCCESS :: $response"
                else
                  echo "FAILED :: $response"
                  exit 1
                fi
              else
                echo "Failed to deploy. HTTP status code: $status_code"
                exit 1
              fi
            
    needs:
      - build-and-push
    permissions: write-all
    runs-on: ubuntu-latest
